---
title: "Functions_not_shown_in_pkgdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*add_access_rules* 

This is a function to add a standard set of access rules to every object so that the access rules don't differ across objects.


*add_admin_group_access*

Add access to the given System Metadata for the arctic-data-admins group

*get_doc_id*

Get the Metacat docid for the given identifier

*env_load*

Load environmental variables from a YAML-formatted environment file.

*get_formats*

Get the list of valid formats from DataONE

*check_format*

Check that the given format is valid. Validity is determined by the given format being found in the list on <https://cn.dataone.org/cn/v2/formats>.

*get_netcdf_format_id*

Determine the DataONE format ID for a NetCDF file provided by path.

*is_format_id*

Test whether an object has a particular format ID

*create_from_folder*

This function  handles the process of inserting the original ISO package and updating it with an EML package.

*view_packages*

Functions for interactive viewing of the inventory and other objects

*inv_init*

Functions relating to keeping up an inventory of files that exist on the KNB and may or may not be copied to another computer and untarred

*inv_load_files*

Load files into the inventory from a text file

*inv_load_checksums*

Load checksums into the inventory file from a text file

*inv_load_dois*

Load DOIs from a text file into the inventory

*inv_load_identifiers*

This function removes the column 'identifier' from inventory before doing a left join.

*inv_add_extra_columns*

Add a set of extra columns to the inventory that are useful for working with them.

*inv_add_parent_package_column*

Add a column for parent packages

*inv_update*

Update an inventory with a new inventory

*theme_packages*

Themes divide packages into groups based upon how the actions we will take to insert them. Packages are divided into one of three themes:

"many-files"

The package has more files than we'd like to include in a Resource Map and we will want to archive its contents before inserting.

"has-versions"

The package has version information embedded into its folder structure. These packages will be hand-verified and inserted manually when a plan is developed to insert them.

"ready-to-go"

All other packages not in the above themes.

*fix_bad_enum*

Fix a metadata record with a bad topicCategory. This is the case where the ISO schema says what's inside a gmd:MD_TopicCategoryCode element should match items from a controlled vocabulary. But in the ISO metadata we have, there are newlines and spaces around that text which causes a check for string equality to fail. i.e. 'oceans' != '     oceans     '

*fix_bad_topic*

Fix a metadata record with multiple MD_TopicCategory children elements inside a single topicCategory element.

*pretty_print*

Use XMLStarlet to pretty-print an XML document. This command just runs `xmlstarlet path > path`, doing a simple pretty-printing of the file located at `path`. Note that this function is doing an in-place pretty printing instead of returning the pretty-printed text.

Note that this command uses a temporary file as an intermediate step in the pretty-printing process. For some reason, when running xmlstarlet from within R, the same file can't be used as the input to `xmlstarlet format` and as the shell redirection file (`> somefile.txt`). If you try to run `xmlstarlet format` on the same file as you redirect to, you get a weird parse error from xmlstarlet.

*insert_file*

Insert a file from a single row of the inventory

*insert_package*

Create a single data package from files in the inventory

*generate_resource_map_pid*

Generate a PID for a new resource map by appending "resource_map_" to it

*get_or_create_pid*

Get the already-minted PID from the inventory or mint a new one

*create_sysmeta*

Create a sysmeta object.

This is a wrapper function around the constructor for a SystemMetadata object.

*create_object*

Create an object from a row of the inventory

*validate_inventory*

Validate an inventory

*validate_environment*

Validate an environment

*determine_child_pids*

Calculate a set of child PIDs for the given package

*update_package*

The modified metadata should be set in the `env` variable. For example, if your original metadata is:

 /home/you/originals/dir/a.xml

and your modified metadata is in

/home/someone_else/modified/dir/a.xml

Then your env should be:

env$base_path <- "/home/you/"
env$alternate_path <- "/home/someone_else"

Note that the data files are not updated either so all that's happening is the metadata object and resource map are being updated.

Note that this function checks if the old objects (metadata and resource map) exist on the Member Node before doing their work and will call createObject() instead of updateObject() if the object didn't already exist

*filter_packaging_statements*

Filter statements related to packaging

This is intended to be called after [datapack::getTriples()] has been called on a resource map.

This function was written specifically for the case of updating a resource map while preserving any extra statements that have been added such as PROV statements.

*replace_subject*

Utility functions for modifying System Metadata objects. Replace subjects in the accessPolicy section of a System Metadata entries. This function was written out to fix capitalization errors in a set of existing System Metadata entries but can be used to replace any subject.

*clear_replication_policy*

Clear the replication policy from a System Metadata object

*extract_local_identifier*

Extract the local identifier for an ACADIS ISO metadata XML file

*show_random_dataset*

Print a random dataset

*log_message*

Log a message to the console and to a logfile. Reads from the environment variable 'LOG_PATH' and uses the value set there to decide the location of the log file. If that envvar isn't set, it defaults to 'arcticdata-log.txt'.

*substitute_eml_party*

Modify name structure for EML parties. Extract the EML responsible-party blocks in a document and parse the
surName field to create proper givenName/surName structure.

*change_eml_name*

Change EML name. Utility function to extract a name string from an XML individualName node, parse it into tokens,and reformat the individualName with new children nodes.

*replace_package_id*

Replace EML packageId with value. Replace the EML 'packageId' attribute on the root element with a certain value.

*add_string_to_title*

Add a string to the title element in the given file

*add_additional_identifiers*

Add a set of additional identifiers to an EML document

*path_join*

Intelligently join possibly redundant path parts together. Joins path strings like "./" to "./my/dir" as "./my/dir" instead of as "././my/dir.

*is_resource_map*

Determine whether the object with the given PID is a resource map

*get_token_subject*

Return the subject of the set dataone_test_token

*get_identifier*

Get the identifier from a DataONE response. Example response:

<d1:identifier xmlns:d1="http://ns.dataone.org/service/types/v1">
urn:uuid:12aaf494-5840-434d-9cdb-c2597d58543e
</d1:identifier>

*get_current_version*

Get the current package version. This function parses the installed DESCRIPTION file to get the latest
version of the package.

*get_latest_release*

Use the GitHub API to find the latest release for the package

*warn_current_version*

Warns if the currently-installed version of the package is not the same version as the latest release on GitHub.

*get_package_direct*

Get a structured list of PIDs for the objects in a package

*find_newest_resource_map*

Get the resource map(s) for the given object

~Note: Why is find_newest_resource_map hidden but not find_newest_object?~ 

*filter_obsolete_pids*

Filters PIDs that are obsolete. Whether or not a PID is obsolete is determined by whether its "obsoletedBy"
property is set to another PID (`TRUE`) or is `NA` (`FALSE`).
